apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-app
spec:
  selector:
    matchLabels:
      app: my-web-app
  replicas: 5
  template:
    metadata:
      name: dagger
      labels:
        app: my-web-app    # Must be the same as the one in the selector
    spec:
      containers:
        - image: madyan74ua/nginx-test
          name: nginx-container
          ports:
            - containerPort: 80
